# Generated by Django 5.0.2 on 2024-03-14 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday')], max_length=5)),
                ('start', models.TimeField(editable=False, max_length=4, verbose_name='Start Time')),
                ('end', models.TimeField(editable=False, max_length=4, verbose_name='End Time')),
                ('location', models.CharField(choices=[('Admin X-ing', 'Admin Crossing'), ('MPH X-ing', 'MPH Crossing'), ('Rear Gate', 'Rear Gate'), ('Primary A', 'Primary A'), ('Primary B', 'Primary B'), ('S. Centre & D Blk', 'Sport Centre & D Block'), ('MPH & Toilets', 'MPH & Chapel Toilets'), ('Oval', 'Oval'), ('Sport Centre', 'Sport Centre w/ Microphone')], max_length=30)),
                ('preset_times', models.CharField(choices=[('8:15 - 8:45', '8:15 AM - 8:45 AM'), ('9:00 - 9:30', '9:00 AM - 9:30 AM')], max_length=30)),
            ],
            options={
                'verbose_name': 'Duty',
                'verbose_name_plural': 'Duties',
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four')], unique=True)),
                ('start', models.DateField(unique=True)),
                ('end', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('current_year', models.IntegerField(editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffDuty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_date', models.DateTimeField(editable=False, null=True)),
                ('duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.duty')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assign Staff',
                'verbose_name_plural': 'Assign Staff',
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.term')),
            ],
        ),
        migrations.AddField(
            model_name='duty',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.term'),
        ),
        migrations.AddField(
            model_name='term',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.year'),
        ),
        migrations.AddConstraint(
            model_name='duty',
            constraint=models.UniqueConstraint(fields=('day', 'start', 'end', 'location'), name='Unique constraint'),
        ),
    ]
