# Generated by Django 5.0.2 on 2024-03-14 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='ref_week',
            field=models.BooleanField(default=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='term',
            name='number',
            field=models.IntegerField(choices=[('One', 1), ('Two', 2), ('Three', 3), ('Four', 4)], unique=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='year',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='home.year'),
        ),
        migrations.AlterField(
            model_name='year',
            name='current_year',
            field=models.IntegerField(default=False, editable=False, unique=True),
        ),
    ]
