# Generated by Django 5.0.2 on 2024-03-14 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_term_ref_week_alter_term_number_alter_term_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='duty',
            name='week',
            field=models.BooleanField(default=True, verbose_name='Wk. A = ON; Wk. B = OFF'),
        ),
        migrations.AlterField(
            model_name='term',
            name='number',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], unique=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='ref_week',
            field=models.BooleanField(default=True, verbose_name='Week A on ODD week numbers'),
        ),
        migrations.AlterField(
            model_name='term',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.year'),
        ),
        migrations.AlterField(
            model_name='year',
            name='current_year',
            field=models.IntegerField(default=2024, editable=False, unique=True),
        ),
    ]
