# Generated by Django 5.0.2 on 2024-03-15 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_duty_week_alter_term_number_alter_term_ref_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duty',
            name='preset_times',
            field=models.CharField(choices=[('8:15 - 8:35', 'Before School 1'), ('8:35 - 9:00', 'Before School 2'), ('10:55 - 11:20', 'Recess'), ('13:00 - 13:25', 'Lunch 1'), ('13:25 - 13:50', 'Lunch 2'), ('15:15 - 15:45', 'After School')], max_length=30),
        ),
        migrations.AlterField(
            model_name='duty',
            name='week',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1),
        ),
    ]
